# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/testing-ios/
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#docker-machine-macos-windows-executor
    macos:
      xcode: 12.5.1 # Specify the Xcode version to use

    steps:
      - checkout

      # Install any dependencies (e.g., CocoaPods)
      - run:
          name: Install Dependencies
          command: |
            bundle exec pod install

      # Build and archive the project
      - run:
          name: Build and Archive
          command: xcodebuild archive -workspace ServeSync.xcworkspace -scheme ServeSync -configuration Release -archivePath build/ServeSync.xcarchive

      # Export IPA file
      - run:
          name: Export IPA
          command: xcodebuild -exportArchive -archivePath build/ServeSync.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist

      # Store IPA file as an artifact
      - store_artifacts:
          path: build/ServeSync.ipa
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
